kind: pipeline
name: AstroJS

steps:
- name: build astro
  image: cimg/node:18.11.0
  commands:
  - npm install
  - npm run build
- name: push to dockerhub
  image: plugins/docker
  settings:
    username: sford1sudo
    password:
      from_secret: dhubpass
    repo: sford1sudo/astro
    tags: latest
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discordwebhookid
    webhook_token: 
      from_secret: discordwebhooktoken
    message: "Astro site has been built and pushed to dockerhub successfully"
