kind: pipeline
name: default

steps:
- name: build astro
  image: node
  commands:
  - npm install
  - npm run build
- name: push to dockerhub
  image: pligins/docker
  settings:
    username: sford1sudo
    password:
      from_secret: dhubpass
    repo: sford1sudo/astro
    tags: latest

