- hosts: webservers
  tasks:
    - name: Install pip
      apt:
        pkg:
          - python3-pip
        state: present
    - name: install docker-py library
      pip:
        name: docker-py

    - name: pull image
      docker_image:
        name: mtabishk/ansible-container-node
        source: pull
    - name: ensure sford1sudo/astro container is running
      docker_container:
        name: astro_website
        state: started
        image: sford1sudo/astro:latest
        restart: yes
        ports:
          - "80:80"
